os: linux
dist: bionic
language: python
python: 3.8
sudo: true
services:
- docker
env:
  global:
  - secure: "Ji3Do+UQhExO46IBKjnAQj0p7EkQKfONyLR55AaF29CvCRDkK0dqsjgfD8QNbInzhTF+sZVTMALkzOOv4PHT3EKpZWHCynunbbiXnN6cs5JHUnEALvPqjDd0sMl1Bs7/bsti7rYtULDGSVn5SbkYP+QlqlmkJd+Fd/+0hFnsW3f8eHqxFwpfdPLN2jXmoHYigYUpM6SrB1L7b2hzEUUM6coEqqwu9bbNF1K5v2DeJWS8/3w7NFLbWJQgVWbBjo6RJWqPC8KDtcvKT6sZUaDUDTmgLMe/RuRgpYHee6RmsgXMMfshYUx6+tsr8CvWJ4BBqEpobsGUgsr7H8t6qqGF4SfnIF8dTr0efWzxOxDBrcNC5dLv8PiBtoABbj/6N4dZBmjOcQuE4clIM+kXLnfCBU5WWB4ayZAXOmXE7/ANDzIfIdMCcZV6TTbX9+wcCIOPyzFcjNaXJXbYmDRjMqm94Zi9uW4Ufx6kCgHp2Cy5N9RVehboBQUPvAmpnSCi+2DIQ9pcM2HNrtDcRGKGdcXV19R3nBrgBE/IigltCjO9W/I6JaahRL/W0Dy4hT4UkPAmVEJyprdVh/94Rz3TR+0XXNp0dKcr1z9m4yYWJPS+JmWHUDaOsxmMQIqFI5u76YyheceS8DpbLcnW5lkjwbN8vvA1uKD/IsHBeIg0i/CDpeA="
  - secure: "rIQ68E/YIqratKbWy0nZfF6TNrVwfb3tfXKiGXRsUsyJiwlpSlOCJciNnEL9Wj++olN5BhWLcfu0EOGPZnGrDiFJvK8wo+TIZtFyofQz3teeWCcOirEDWnlSIIWsCVHtw1x07fZK5Fo3KIY99+OAJxGIlvGT1xt2n4lBnwUQ2pQxgHIUsonKRdS0XyuXF2p1zZr5hNKE3zX0aiifzMilQ1YjrcU70rz607LHDR5Yz8VBl0KCZUKp/yGaVesGYwXa+MWtJRChR5RtElDPaRJo5Uun6QO9uy/TkyDOhv3ecSwC6RS5NBVuWmi7JV2m0nGFghEFI49X5lPYa7SRi6u+bV4lu4pvrLHs9GOjwc3Vvzbpo4t9e3+leeyv1fvz0sGHzFvOURHuqqyYpLTeyXt6E12T7TPbmRrg2+5TNWo24vD9JQ6Zom008Vm+H/1+5nWxiQ6AtX/1YR5ZFUc5RpY8VT1QMg3XhTVsawsJrgpsFqC4bS2HN1FkV6wHESZsvP4kIwEJW6B2KC0oIOf5QpBBE8bxM5WO70ay8OtvPujhPGF0G5i5c3ZEED1F0GXc++bEK9bTfEG6c0S3cZlKKL3pXcyhtBngFoDj6IMIgRA/SSsvwV6xA7irwvfjhZOtwNqjmYm1TyVfg9rL2XneCWkmix4HClDQfjg9dFPKMEhlK0g="
jobs:
  include:
    # TODO: Only perform this step if the file deps.Dockerfile changed.
    # https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-stages
    # https://stackoverflow.com/a/38550849/2769475
    # https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
    #- stage: build deps image
    #  script:
    #  - docker build --no-cache -t scale-mamba-deps -f deps.Dockerfile .
    #  - echo "$DOCKER_USERNAME"
    #  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    #  - docker tag scale-mamba-deps $DOCKER_USERNAME/scale-mamba-deps
    #  - docker push $DOCKER_USERNAME/scale-mamba-deps
    - stage: build image
      script:
      - docker build --no-cache -t scale-mamba -f py2.Dockerfile .
      - echo "$DOCKER_USERNAME"
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag scale-mamba $DOCKER_USERNAME/scale-mamba
      - docker push $DOCKER_USERNAME/scale-mamba
    - stage: test
      name: test set 1
      env: TEST_SET=1
      script:
      - .ci/before_test.sh
      # TODO: re-use an image that has make test already done
      #- docker run --rm $DOCKER_USERNAME/scale-mamba make test
      - docker run --rm $DOCKER_USERNAME/scale-mamba sh .ci/run_tests.sh
    - stage: doc
      script: docker run --rm $DOCKER_USERNAME/scale-mamba make doc
