os: linux
dist: bionic
language: python
python: 3.8
sudo: true
services:
- docker
env:
  global:
  - secure: JEeNF1tMdjKgcddNRzUCsfINA2meTFLQ5ltqEg40/rWkv3V6s2qgYAtLoC5SoKulb8xMDgIQiVHpQiHNeAjATiX9qYEHl9FEmrFkv03mDFJIlPDtgZ5RQwoBnWrNqlX62nvWaO3/qfISovwIbnIp15k1ULvUN1oPr5Egr+CNmzTktXOXCZchKW55GjJAeSM4EgVLH/5LM2bisEEAlVCz+catmvZDkkiHmy1mq1FM9/DwgonkATPHIOs4Enkicc20nVtx2iRrNKFkMzQbzplrLkJCjZcYVjvIN0mB8cOIGHS6dOy7aApQbZ1tQzLCehy+5rLNKw8PZnNzLrBocQ0lV/NzzKI7vwYfaYUmRzEh3kO7WZV6oUllaRy6+Y+edPd7GCstBkwp8W/Xi9CHdQavDahqtR/S21KvatbGnLWl1LKVI4FePYB4YelKqzB0tKxOS40xdpIKydbH01K2kqbZlqWicAyN4bk4N4NumnoCJix5Ep3Me0wYJkiOEiNMsSz+7kEbKoiG7hKmLsD8ZgAVPXgpFIZ25GwQqmJG60P7Ao4DWFtIfOoSMBtNgx+em7f3BRPzM9gJ0hQFfAAhwnsk+VEDq8B6B1sRKh8dk8/UDKE+gDCPBLr/q/p+9Q9xg3G3MxbTdc15+pj5mPO7jHBcQeMLzPyLUhYIupFZatMbppE=
  - secure: m+9eff9yq+mLX6bGAVeWHf0hZjQH4oWIiksZzKQas2y8Ew+qhXM+zNaqgkot7Ewh+gpsSvAHE/hvqc08nCVg46zErw+/pJXVNfE/4qGwyJ9tQdBShdWCP16eKQaoBk8TYM4sUBA8E8hYieC0TLYJTmbV6lVhrYurB8m+lsN0AkPI3O3kavTXSluUmBTEpOkAgGT3KCDvsAAr9vQWwX3RJroLWsO/3fBHe64eCkvIgyaEtMIdHL5Sjlk2ARA+yFYB6PoAb7hPGAIjf+zBUY68A+DkgyA3wxdYFzLCeUWd1vPVMai3v6wHBnqERNvpkeriYkU3VOBnMr7SwWVeTuMA1kAl3jrww/l0ewwFvNwAqeDhP4VSHt1amPk25B9B34048ncpCIoE0UyCGQQM+y+SxjQbhYGcWJOz8fMk+2GICFiAkyYtk8wQD/85XErQFfBU/YqbFPDGjzXvj/nMj78P6Rr0Kc81riP3gsmoKp3ElpO8tpGRztKWGgMwfKk0tFoC/oADBcPrHSiJ0YXuvIx8ucPdNKl4Mb9dBXre/93m6DbTtqgcakOtvo1ASkfocKqPGyyGw80HHbJAhgU/CTipR63ONEjEP59fo8fKWryIJ4am3nVZq0jbE5gmkLmgfEbg8VdcurAQyrIj7EPMkVJY48TfG19y0VhnMMYdQ22K5Vg=
jobs:
  include:
    # TODO: Only perform this step if the file deps.Dockerfile changed.
    # https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-stages
    # https://stackoverflow.com/a/38550849/2769475
    # https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
    #- stage: build deps image
    #  script:
    #  - docker build --no-cache -t scale-mamba-deps -f deps.Dockerfile .
    #  - echo "$DOCKER_USERNAME"
    #  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    #  - docker tag scale-mamba-deps $DOCKER_USERNAME/scale-mamba-deps
    #  - docker push $DOCKER_USERNAME/scale-mamba-deps
    - stage: build image
      script:
      - docker build --no-cache -t scale-mamba -f py2.Dockerfile .
      - echo "$DOCKER_USERNAME"
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag scale-mamba $DOCKER_USERNAME/scale-mamba
      - docker push $DOCKER_USERNAME/scale-mamba
    - stage: test
      name: test set 1
      env: TEST_SET=1
      script:
      - ./before_test.sh
      # TODO: re-use an image that has make test already done
      - docker run --rm $DOCKER_USERNAME/scale-mamba make test
      - docker run --rm $DOCKER_USERNAME/scale-mamba sh .ci/run_tests.sh
    - stage: doc
      script: docker run --rm $DOCKER_USERNAME/scale-mamba make doc
