version: 2
jobs:
  build:
    machine: true
    environment:
      TEST_SET: 1
      PROGRAMS: "test_array test_branch test_branching test_comparison test_empty_tape test_flex test_float test_floatingpoint test_float_sorting test_float_vector test_function test_idle_threads test_lib test_loop test_mem_order test_sregint test_vector test_sfix test_sqrt test_custom_array test_fix_array test_all"
    steps:
      - checkout
      - run: docker build --no-cache -t scale-mamba -f py2.Dockerfile .
      - run: .circleci/test-programs.sh
