version: 2
jobs:
 build:
   machine: true
   environment:
      PROGRAMS: "test_array test_branch"
   steps:
     - checkout
     - run: docker build --no-cache -t scale-mamba -f py2.Dockerfile .
     - run: .circleci/test-programs.sh
